Converting docstrings to NatSpec format
Carbonable/carbon-protocol pull request #160
Opened 2023-02-19 16:30 UTC by Marchand-Nicolas

2023-02-19 16:47 UTC, Bal7hazar requested changes
Nice job

1. Missing a cap letter for param and return description, for instance:
`@param test this is a test` must be `@param test This is a test`

2. Short description must be in imperative mood:
`@notice Returns something` must be `@notice Return something`

3. If possible, try to add an article in param and return description:
`@param test Test` must be `@param test The test`

2023-02-19 16:47 UTC, Bal7hazar commented on src/vesting/vester.cairo
>      account: felt
Missing account param

2023-02-19 16:47 UTC, Bal7hazar commented on src/badge/library.cairo
>      func initializer{
Param descriptions must start with a cap char

2023-02-19 16:47 UTC, Bal7hazar commented on src/badge/library.cairo
> +    // @notice Initializes the contract with the given signer public key and badge contract address.
Imperative mood in the descriptions, so no "s" for Initialize

2023-02-19 16:47 UTC, Bal7hazar commented on src/badge/library.cairo
> +    // @param badge_contract_address badge contract address.
Param descriptions must start with a cap char

2023-02-19 16:47 UTC, Bal7hazar commented on src/badge/library.cairo
> +    // @notice Returns the public key of the signer.
Imperative mood

2023-02-19 16:47 UTC, Bal7hazar commented on src/badge/library.cairo
> +    // @return signer_public_key signer public key.
Cap char for description

2023-02-19 16:47 UTC, Bal7hazar commented on src/badge/library.cairo
> +    // @notice Returns the address of the badge contract.
Imperative mood

2023-02-19 16:47 UTC, Bal7hazar commented on src/badge/library.cairo
> +    // @return badge_contract_address badge contract address.
Cap char for description

2023-02-19 16:47 UTC, Bal7hazar commented on src/badge/library.cairo
> +    // @param badge_type badge type.
Cap char for description, also try to add an article in descriptions such as "The badge type" instead of "badge type"

2023-02-19 16:47 UTC, Bal7hazar commented on src/mint/minter.cairo
> +// @return status 1 if sold out else 0.
Could you replace 1 and 0 by TRUE and FALSE is these examples please?

2023-02-20 19:30 UTC, Bal7hazar requested changes

2023-02-20 19:30 UTC, Bal7hazar commented on src/badge/library.cairo
>      func initializer{
@Marchand-Nicolas, you miss this one I think

2023-02-20 19:36 UTC, Bal7hazar requested changes

2023-02-20 19:36 UTC, Bal7hazar commented on src/mint/minter.cairo
> +// @return max_buy_per_tx Max number of NFTs that can be purchased in a single tx.
Wrong Copy/Paste I guess

2023-02-20 19:36 UTC, Bal7hazar commented on src/vesting/vester.cairo
>      account: felt
Still

2023-02-20 19:36 UTC, Bal7hazar commented on src/badge/library.cairo
> +    // @notice Initializes the contract with the given signer public key and badge contract address.
Still

2023-02-20 19:36 UTC, Bal7hazar commented on src/badge/library.cairo
> +    // @param badge_contract_address badge contract address.
Still

2023-02-20 19:43 UTC, Bal7hazar requested changes

2023-02-20 19:43 UTC, Bal7hazar commented on src/mint/minter.cairo
> +// @return max_buy_per_tx The max number of NFTs that can be purchased in a single tx.
Wrong Copy/Paste

2023-02-20 19:43 UTC, Bal7hazar commented on src/mint/minter.cairo
> +// @return max_buy_per_tx The max number of NFTs that can be purchased in a single tx.
Wrong Copy/Paste

2023-02-20 19:43 UTC, Bal7hazar commented on src/mint/minter.cairo
> +// @return max_buy_per_tx The max number of NFTs that can be purchased in a single tx.
Wrong Copy/Paste

2023-02-20 19:43 UTC, Bal7hazar commented on src/mint/minter.cairo
> +// @return max_buy_per_tx The max number of NFTs that can be purchased in a single tx.
Wrong Copy/Paste

2023-02-20 19:43 UTC, Bal7hazar commented on src/mint/minter.cairo
> +//   Their must be enough available reserved NFTs regarding reserved supply.
Their -> There

2023-02-21 08:03 UTC, Bal7hazar requested changes

2023-02-21 08:03 UTC, Bal7hazar commented on src/mint/minter.cairo
> +// @return max_buy_per_tx The max number of NFTs that can be purchased in a single tx.
Wrong description

2023-02-21 08:03 UTC, Bal7hazar commented on src/mint/minter.cairo
> +// @return max_supply_for_mint The max supply.
Wrong description

2023-02-21 08:15 UTC, Bal7hazar approved these changes
LGTM

2023-02-21 08:15 UTC, Marchand-Nicolas commented
It took me around 3 hours.

2023-02-21 09:38 UTC, merged